- name: Install PHP from Remi repo
  yum: enablerepo=remi name={{ item }} state=present
  with_items:
    - php
    - php-cli
    - php-mbstring
    - php-mysql
    - php-xml
    - php-gd
  notify: restart apache
  tags:
    - php

